AWSTemplateFormatVersion: "2010-09-09"
Description: "Setup da conta DevOps - Contem o repositorio SharedLibrary"

Parameters:
  RepositoryName:
    Description: Name of the Project
    Type: String
    Default: sharedlibrary

Resources:

  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: Repositorio de Bibliotecas Compartilhadas

Outputs:
  RepositoryName:
    Value: !Ref RepositoryName