AWSTemplateFormatVersion: '2010-09-09'
Description: Criação do Repo e Bucket para SharedLib 

Parameters:
  DevToolsAccount:
    Description: DevAccount
    Type:  Number
  DevAccount:
    Description: DevAccount
    Type:  Number
  HomologAccount:
    Description: HomologAccount
    Type:  Number
  ProdAccount:
    Description: ProdAccount
    Type:  Number
    
Resources:
  CodeCommiSharedLibs:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: sharedlibs
      RepositoryDescription: Repositorio de Shares Libs

  TemplateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub templates-${AWS::AccountId}

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TemplateBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${TemplateBucket}
              - !Sub arn:aws:s3:::${TemplateBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DevAccount}:root
                - !Sub arn:aws:iam::${HomologAccount}:root
                - !Sub arn:aws:iam::${ProdAccount}:root
                - !Sub arn:aws:iam::${DevToolsAccount}:root
          -
            Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${TemplateBucket}
              - !Sub arn:aws:s3:::${TemplateBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

Outputs:
  TemplateBucket:
    Description: TemplateBucket
    Value: !Ref TemplateBucket