AWSTemplateFormatVersion: '2010-09-09'
Description: Criação da CrossAccountRole nas contas Dev, Homolog e Prod

Parameters:
  DevToolsAccount:
    Description: DevToolsAccount
    Type:  String
  BucketArtifact:
    Description: BucketArtifact
    Type:  String
  KMSKeyArn:
    Description: KMSKeyArn
    Type:  String

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccountRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref DevToolsAccount
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  CrossAccountPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CrossAccountPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - cloudformation:*
              - s3:*
              - iam:*
              - events:*
              - ec2:*
              - lambda:*
              - logs:*
              - ecs:*
              - ecr:*
              - elasticloadbalancing:*
              - autoscaling:*
              - application-autoscaling:*
              - cloudwatch:*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
            Resource:
             - !Join ['',['arn:aws:s3:::',!Ref BucketArtifact, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref BucketArtifact]]
          - 
            Effect: Allow
            Action:
              - kms:*
            Resource: !Ref KMSKeyArn
      Roles:
        -
          !Ref CrossAccountRole