AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DevOpsAccount:
    Description: DevToolsAccount
    Type:  Number
  DevToolsAccount:
    Description: DevToolsAccount
    Type:  Number
  DevAccount:
    Description: DevAccount
    Type:  Number
  HomologAccount:
    Description: HomologAccount
    Type:  Number
  ProdAccount:
    Description: ProdAccount
    Type:  Number

Resources:

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - ssm:*
            Resource: "*" 
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      Roles:
        -
          !Ref CodeBuildServiceRole

  CodePipeLineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  CodePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodePipelinePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - codepipeline:*
              - iam:ListRoles
              - cloudformation:Describe*
              - cloudFormation:List*
              - codecommit:List*
              - codecommit:Get*
              - codecommit:GitPull
              - codecommit:UploadArchive
              - codecommit:CancelUploadArchive
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
              - iam:PassRole
            Resource:
              - "*"
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - s3:*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - ssm:*
            Resource: "*" 
          -
            Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !Sub arn:aws:iam::${DevAccount}:role/ToolsAcctCodePipelineCloudFormationRole
              - !Sub arn:aws:iam::${DevAccount}:role/cloudformationdeployer-role
              - !Sub arn:aws:iam::${HomologAccount}:role/ToolsAcctCodePipelineCloudFormationRole
              - !Sub arn:aws:iam::${HomologAccount}:role/cloudformationdeployer-role
              - !Sub arn:aws:iam::${ProdAccount}:role/ToolsAcctCodePipelineCloudFormationRole
              - !Sub arn:aws:iam::${ProdAccount}:role/cloudformationdeployer-role
              - !Sub arn:aws:iam::${DevToolsAccount}:role/ToolsAcctCodePipelineCloudFormationRole
              - !Sub arn:aws:iam::${DevToolsAccount}:role/cloudformationdeployer-role
              - !Sub arn:aws:iam::${DevOpsAccount}:role/RoleCrossAccount
      Roles:
        -
          !Ref CodePipeLineServiceRole

  CodePipeLineServiceRoleParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/Shared/Roles/CodePipeline"
      Type: "String"
      Value: !GetAtt CodePipeLineServiceRole.Arn
      Description: "CodePipeLineServiceRole"

  CodeBuildServiceRoleParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/Shared/Roles/CodeBuild"
      Type: "String"
      Value: !GetAtt CodeBuildServiceRole.Arn
      Description: "CodeBuildServiceRole"