AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DevToolsAccount:
    Description: AWS AccountNumber for DevTools Account
    Type: String

  KMSKeyArn:
    Type: String
    Default: arn:aws:kms:sa-east-1:935187548418:key/3adbf5d0-a9a9-449d-b5b3-3f3473d6c1f3


Resources:

  RoleCrossAccount:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
    Properties:
      RoleName: RoleCrossAccount
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref DevToolsAccount
            Action:
              - sts:AssumeRole
      Path: /
      Policies: 
        - 
          PolicyName: "DevOpsPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  PolicyCrossAccount:
    Type: AWS::IAM::Policy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F4
    Properties:
      PolicyName: DevOpsPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - codecommit:BatchGetRepositories
              - codecommit:Get*
              - codecommit:GitPull
              - codecommit:List*
              - codecommit:CancelUploadArchive
              - codecommit:UploadArchive
              - codebuild:*
              - cloudformation:*
              - iam:*
              - s3:*
              - kms:*
            Resource: "*"
      Roles:
        -
          !Ref RoleCrossAccount


 