AWSTemplateFormatVersion: "2010-09-09"
Description: "Setup da conta DevTools"

Parameters:
  FeatureName:
    Description: Nome da Feature
    Type:  String

  TemplateName:
    Description: Template da pipeline
    Type:  String
    Default: 'microservice-001' 
    AllowedValues:  
      - 'microservice-001' 
      - 'microservice-002'  
      - 'mobile-android-001'  
      - 'mobile-android-002'  
      - 'mobile-ios-001'  
      - 'mobile-ios-002'  
      - 'web-3tier-001'  
      - 'web-3tier-002'  

  Runtime: 
    Description: Runtime da aplicacao
    Type: String 
    AllowedValues:  
      - 'java: openjdk8' 
      - 'java: openjdk11'  
      - 'dotnet: 2.2' 
      - 'python: 3.7' 

  MicroServiceName:
    Description: Nome do microservico (nome do repositorio)
    Type:  String

  BranchName:
    Description: Nome da Branch
    Type:  String
    Default: "master"

  DevOpsAccount:
    Description: DevOpsAccount
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Accounts/DevOps'

  DevAccount:
    Description: DevAccount
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Accounts/Dev'

  HomologAccount:
    Description: HomologAccount
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Accounts/Homolog'

  ProdAccount:
    Description: ProdAccount
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Accounts/Prod'

  CodePipeLineServiceRole:
    Description: CodePipeLineServiceRole
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Roles/CodePipeline'

  BucketArtifact:
    Description: BucketArtifact
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Shared/BucketArtifact'

  KMSKeyArn:
    Description: KMSKeyArn
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Shared/KMSKeyArn'

  CodeBuildServiceRole:
    Description: CodeBuildServiceRole
    Type:  'AWS::SSM::Parameter::Value<String>' 
    Default: '/Roles/CodeBuild'

Metadata:  
  AWS::CloudFormation::Interface:  
    ParameterGroups:  
      -  
        Label:  
          default: "PREENCHIMENTO OBRIGATORIO" 
        Parameters:  
          - FeatureName 
          - MicroServiceName 
          - Runtime 
      -  
        Label:  
          default: "NAO FACA ALTERACOES AQUI" 
        Parameters:  
          - BranchName
          - TemplateName
          - DevOpsAccount
          - DevAccount
          - HomologAccount
          - ProdAccount 
          - BucketArtifact
          - KMSKeyArn
          - CodeBuildServiceRole
          - CodePipeLineServiceRole

Conditions: 
  ContinuousDelivery: !Or
    - !Equals ["master", !Ref BranchName]
    - !Equals ["develop", !Ref BranchName]
  BranchMaster: !Equals [ "master", !Ref BranchName ]

Resources:

  Repository:
    Type: AWS::CodeCommit::Repository
    Condition: BranchMaster
    Properties:
      RepositoryName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName']]
      RepositoryDescription: Repositorio do Micro Servico

  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', !Ref 'BranchName']]
      RoleArn: !Ref CodePipeLineServiceRole
      ArtifactStore:
        Type: S3
        Location: !Ref BucketArtifact
        EncryptionKey:
          Id: !Ref KMSKeyArn
          Type: KMS

      Stages:
        - Name: Source
          Actions:
            - Name: Source-App
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeCommit
              Configuration:
                RepositoryName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName']]
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SourceApp
              RunOrder: 1
            - Name: "Source-SharedLibs"
              RoleArn: !Sub "arn:aws:iam::${DevOpsAccount}:role/RoleCrossAccount"
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: master
                RepositoryName: sharedlibrary
                PollForSourceChanges: false
              InputArtifacts: []
              OutputArtifacts:
                - Name: "SharedLibs"
              RunOrder: 1
 
        - Name: Build
          Actions:
            - Name: TestesUnitarios
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Out-TestesUnitarios
              InputArtifacts:
                - Name: SourceApp
                - Name: SharedLibs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'TestesUnitarios' ]]
                PrimarySource: SharedLibs
              RunOrder: 1

            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Out-BuildApp
              InputArtifacts:
                - Name: SourceApp
                - Name: SharedLibs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'Build' ]]
                PrimarySource: SharedLibs
              RunOrder: 1

            - Name: Sonar
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Out-Sonar
              InputArtifacts:
                - Name: SourceApp
                - Name: SharedLibs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'Sonar' ]]
                PrimarySource: SharedLibs
              RunOrder: 1

            - Name: Fortify
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Out-Fortify
              InputArtifacts:
                - Name: SourceApp
                - Name: SharedLibs
              Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Fortify' ]]
                  PrimarySource: SharedLibs
              RunOrder: 1

            - Name: Aqua
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Out-Aqua
              InputArtifacts:
                - Name: SourceApp
                - Name: SharedLibs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'Aqua' ]]
                PrimarySource: SharedLibs
              RunOrder: 2

        - !If 
          - ContinuousDelivery 
          - Name: Publish
            Actions:
              - Name: Publish
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                  - Name: Out-Publish
                InputArtifacts:
                  - Name: SourceApp
                  - Name: SharedLibs
                Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Publish' ]]
                  PrimarySource: SharedLibs
                RunOrder: 3
          - !Ref AWS::NoValue 

        - !If 
          - ContinuousDelivery 
          - Name: Testes
            Actions:
              - Name: Testes
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                  - Name: Out-Testes
                InputArtifacts:
                  - Name: SourceApp
                  - Name: SharedLibs
                Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Testes' ]]
                  PrimarySource: SharedLibs
                RunOrder: 3
          - !Ref AWS::NoValue 

        - !If 
          - ContinuousDelivery 
          - Name: Deploy
            Actions:
              - Name: Deploy
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                  - Name: Out-Deploy
                InputArtifacts:
                  - Name: SourceApp
                  - Name: SharedLibs
                Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Deploy' ]]
                  PrimarySource: SharedLibs
                RunOrder: 3
          - !Ref AWS::NoValue 

  Deploy:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Deploy' ]]
      Description: Deploy
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/deploy.yml
      TimeoutInMinutes: 10

  Testes:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Testes' ]]
      Description: Testes 
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/testes.yml
      TimeoutInMinutes: 10

  TestesUnitarios:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'TestesUnitarios' ]]
      Description: Testes Unitarios
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/unittests.yml
      TimeoutInMinutes: 10

  Build:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Build' ]]
      Description: Build da Aplicação
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/build.yml
      TimeoutInMinutes: 10

  Sonar:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Sonar' ]]
      Description: Sonar
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/sonar.yml
      TimeoutInMinutes: 10

  Fortify:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Fortify' ]]
      Description: Fortify
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/fortify.yml
      TimeoutInMinutes: 10

  Aqua:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Aqua' ]]
      Description: Aqua
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/aqua.yml
      TimeoutInMinutes: 10

  Publish:
    Type: AWS::CodeBuild::Project
    Condition: BranchMaster
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Publish' ]]
      Description: Publish
      EncryptionKey: !Ref KMSKeyArn
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/publish.yml
      TimeoutInMinutes: 10

  TemplateNameParameter:
    Type: "AWS::SSM::Parameter"
    Condition: BranchMaster
    Properties:
      Name: !Sub TemplateName-${FeatureName}-${MicroServiceName}
      Type: "String"
      Value: !Ref TemplateName

  RuntimeParameter:
    Type: "AWS::SSM::Parameter"
    Condition: BranchMaster
    Properties:
      Name: !Sub Runtime-${FeatureName}-${MicroServiceName}
      Type: "String"
      Value: !Ref Runtime