version: 0.2 
phases:
  install:
    runtime-versions:
      dotnet: 2.2
  build: 
    commands: 
      - echo Executando o testUnit
      - dotnet test test/HelloWorldJenkins.UnitTests
  post_build:
    commands:
      - echo "Post Build"
      - ls

